module.exports = {
  400: ['BAD_REQUEST', 400],
  401: ['UNAUTHORIZED', 401],
  404: ['NOT_FOUND', 404],
  500: ['INTERNAL_SERVER_ERROR', 500],

  WITHDRAWN: ['최근 6개월 이내 탈퇴한 이력이 있습니다.\n동일한 이메일 또는 SNS로 재가입을 원하실 경우 탈퇴일로부터 6개월 후 가능합니다.', 409],
  INACTIVATED: ['휴면 회원입니다.', 403],
  JsonWebTokenError: ['유효하지 않은 토큰입니다.', 401],
  INVALID_NICKNAME: ['2~10자의 한글, 영어, 숫자, 기본특수문자 조합만 가능합니다', 409],
  INVALID_PASSWORD: ['비밀번호는 8자~24자 이하로 영문 대문자, 소문자, 숫자, 특수문자 중에 2개 이상 조합되어야 합니다', 409],
  TokenExpiredError: ['토큰이 만료되었습니다.', 401],
  INVALID_EMAIL: ['올바른 이메일이 아닙니다.', 409],
  CANNOT_DELETE_SNS: ['비밀번호가 설정되어 있지 않아 SNS 연결을 해제할 수 없습니다.', 409],
  DUPLICATED_SNS: ['이미 등록된 SNS 계정입니다.', 409],
  NO_ADMIN_ACCOUNT: ['로그인 정보가 올바르지 않습니다.', 404],
  NO_ALLOW_IP: ['해당 계정은 외부에서의 접속이 허용되지 않았습니다.', 401],
  NOT_CERTIFIED_EMAIL: ['인증되지 않은 이메일입니다.', 401],
  INVALID_SECRETCODE: ['인증번호가 틀립니다.', 401],
  INVALID_CERTIFIED_CODE: ['유효한 인증번호가 아닙니다.', 401],
  USED_EMAIL: ['이미 사용중인 이메일입니다', 409],
  USED_NICKNAME: ['이미 사용중인 닉네임입니다', 409],
  WITHDRAW_HAD_RESERVATION: ['진행중인 예약건이 있어 회월탈퇴할 수 없습니다.', 403],
}
